# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_auto_20160702_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='published_date',
            new_name='modified_date',
        ),
    ]
